import { describe, expect, it } from "vitest";
import {
  DEFAULT_MAX_OUTPUT_TOKENS,
  estimateInputTokens,
  generatedBytes,
  MAX_OUTPUT_TOKENS,
  parseChatRequest,
  readUsage,
} from "../lib/server/gateway/request";
import { SseSplitter } from "../lib/server/gateway/sse";
import { scrub, upstreamErrorMessage } from "../lib/server/gateway/upstream";
import { ApiError } from "../lib/server/http";

const msgs = [{ role: "user", content: "hi" }];

describe("parseChatRequest", () => {
  it("keeps supported fields, drops the rest, and always sets max_tokens", () => {
    const tools = [{ type: "function", function: { name: "f", parameters: { type: "object" } } }];
    const r = parseChatRequest({
      model: "gpt-4o",
      messages: msgs,
      tools,
      tool_choice: "auto",
      temperature: 0.2,
      stop: ["\n\n"],
      user: "someone",
      logprobs: true,
      n: 1,
      stream: true,
      stream_options: { include_usage: true },
    });
    expect(r.body).toEqual({ messages: msgs, tools, tool_choice: "auto", temperature: 0.2, stop: ["\n\n"], max_tokens: DEFAULT_MAX_OUTPUT_TOKENS });
    expect(r).toMatchObject({ stream: true, includeUsage: true, maxTokens: DEFAULT_MAX_OUTPUT_TOKENS });
  });

  it("reads max_completion_tokens or max_tokens and clamps huge values", () => {
    expect(parseChatRequest({ messages: msgs, max_tokens: 100 }).maxTokens).toBe(100);
    expect(parseChatRequest({ messages: msgs, max_completion_tokens: 50, max_tokens: 100 }).maxTokens).toBe(50);
    expect(parseChatRequest({ messages: msgs, max_tokens: 10_000_000 }).maxTokens).toBe(MAX_OUTPUT_TOKENS);
    expect(parseChatRequest({ messages: msgs, stream_options: { include_usage: true } }).includeUsage).toBe(false);
  });

  it("rejects what the gateway cannot meter", () => {
    const code = (raw: Record<string, unknown>) => {
      try {
        parseChatRequest(raw);
        return "ok";
      } catch (e) {
        return (e as ApiError).code;
      }
    };
    expect(code({})).toBe("invalid_messages");
    expect(code({ messages: [] })).toBe("invalid_messages");
    expect(code({ messages: [{ role: "wizard", content: "x" }] })).toBe("invalid_messages");
    expect(code({ messages: [{ role: "user", content: 5 }] })).toBe("invalid_messages");
    expect(code({ messages: msgs, tools: {} })).toBe("invalid_tools");
    expect(code({ messages: msgs, n: 3 })).toBe("unsupported_n");
    expect(code({ messages: msgs, max_tokens: 0 })).toBe("invalid_max_tokens");
    expect(code({ messages: msgs, max_tokens: 1.5 })).toBe("invalid_max_tokens");
    expect(code({ messages: msgs, stream: "yes" })).toBe("invalid_stream");
  });
});

describe("estimates", () => {
  it("over-reserves input at 3 bytes per token and counts tools", () => {
    const text = "x".repeat(3000);
    const base = estimateInputTokens({ messages: [{ role: "user", content: text }] });
    expect(base).toBeGreaterThanOrEqual(1000);
    expect(base).toBeLessThan(1100);
    const withTools = estimateInputTokens({ messages: [{ role: "user", content: text }], tools: [{ big: "y".repeat(3000) }] });
    expect(withTools - base).toBeGreaterThanOrEqual(1000);
    // Multi-byte text is not undercounted: 1000 CJK chars are 3000 bytes.
    expect(estimateInputTokens({ messages: [{ role: "user", content: "字".repeat(1000) }] })).toBeGreaterThanOrEqual(1000);
  });

  it("counts generated bytes across content, reasoning and tool calls", () => {
    expect(generatedBytes({ content: "abc", reasoning_content: "de", tool_calls: [{ function: { name: "fn", arguments: '{"a":1}' } }] })).toBe(3 + 2 + 2 + 7);
    expect(generatedBytes(null)).toBe(0);
  });

  it("reads usage only when well formed", () => {
    expect(readUsage({ prompt_tokens: 3, completion_tokens: 4, total_tokens: 7 })).toEqual({ inputTokens: 3, outputTokens: 4 });
    expect(readUsage({ prompt_tokens: -1, completion_tokens: 4 })).toBeNull();
    expect(readUsage({ prompt_tokens: "3", completion_tokens: 4 })).toBeNull();
    expect(readUsage(null)).toBeNull();
  });
});

describe("SseSplitter", () => {
  it("reassembles events split across chunks and line-ending styles", () => {
    const s = new SseSplitter();
    expect(s.push('data: {"a"')).toEqual([]);
    expect(s.push(':1}\n')).toEqual([]);
    expect(s.push("\ndata: two\r")).toEqual([{ data: '{"a":1}', raw: 'data: {"a":1}' }]);
    expect(s.push("\n\r\n: keep-alive\r\n\r\ndata: [DONE]")).toEqual([
      { data: "two", raw: "data: two" },
      { data: null, raw: ": keep-alive" },
    ]);
    expect(s.flush()).toEqual([{ data: "[DONE]", raw: "data: [DONE]" }]);
    expect(s.flush()).toEqual([]);
  });

  it("joins multi-line data", () => {
    expect(new SseSplitter().push("data: a\ndata:b\n\n")).toEqual([{ data: "a\nb", raw: "data: a\ndata:b" }]);
  });
});

describe("upstream messages", () => {
  const target = { baseUrl: "https://api.runpod.ai/v2/abc123/openai/v1", apiKey: "rp_secret_key" };

  it("never leak the upstream URL, host or key", () => {
    const out = scrub("failed calling https://api.runpod.ai/v2/abc123/openai/v1/chat with rp_secret_key at api.runpod.ai", target);
    expect(out).not.toContain("runpod");
    expect(out).not.toContain("rp_secret_key");
    expect(scrub("x".repeat(2000), target)).toHaveLength(500);
  });

  it("extract messages from OpenAI and vLLM error shapes", () => {
    expect(upstreamErrorMessage('{"error":{"message":"too long"}}')).toBe("too long");
    expect(upstreamErrorMessage('{"message":"bad","type":"BadRequestError"}')).toBe("bad");
    expect(upstreamErrorMessage('{"detail":"nope"}')).toBe("nope");
    expect(upstreamErrorMessage("<html>")).toBe("");
  });
});
